// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCobr2XsyBS2NG7zPSphrxwze8fziYz8Ao',
    appId: '1:430324050449:web:b0f08af490a7d855de1fb0',
    messagingSenderId: '430324050449',
    projectId: 'desafio-dwu',
    authDomain: 'desafio-dwu.firebaseapp.com',
    databaseURL: 'https://desafio-dwu-default-rtdb.firebaseio.com',
    storageBucket: 'desafio-dwu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH5-3SrfAL65c-1jpexIZ-tFpFSiVHWmc',
    appId: '1:430324050449:android:41b2fc5d4f10a718de1fb0',
    messagingSenderId: '430324050449',
    projectId: 'desafio-dwu',
    databaseURL: 'https://desafio-dwu-default-rtdb.firebaseio.com',
    storageBucket: 'desafio-dwu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC92Ne3t5NCyyszckB-4Q-k02sc0VhVjz0',
    appId: '1:430324050449:ios:613126a091b23b16de1fb0',
    messagingSenderId: '430324050449',
    projectId: 'desafio-dwu',
    databaseURL: 'https://desafio-dwu-default-rtdb.firebaseio.com',
    storageBucket: 'desafio-dwu.appspot.com',
    iosClientId: '430324050449-97v9qn0dllm40glt6ll1smt99mkq5bo3.apps.googleusercontent.com',
    iosBundleId: 'com.example.dwuDesafio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC92Ne3t5NCyyszckB-4Q-k02sc0VhVjz0',
    appId: '1:430324050449:ios:613126a091b23b16de1fb0',
    messagingSenderId: '430324050449',
    projectId: 'desafio-dwu',
    databaseURL: 'https://desafio-dwu-default-rtdb.firebaseio.com',
    storageBucket: 'desafio-dwu.appspot.com',
    iosClientId: '430324050449-97v9qn0dllm40glt6ll1smt99mkq5bo3.apps.googleusercontent.com',
    iosBundleId: 'com.example.dwuDesafio',
  );
}
